#
# Makefile
#

target :
	gcc -Wall -g -o l02e01A l02e01A.c -lpthread
	gcc -Wall -g -o l02e01B l02e01B.c -lpthread
	gcc -Wall -g -o l02e01C l02e01C.c -lpthread
	gcc -Wall -g -o l02e02 l02e02.c -lpthread


clean :
	rm -f *.o
	rm -rf l02e01A l02e01B l02e01C l02e02

distclean : clean
	rm -rf core
	rm -rf *~
